// Conformance harness replaying packages/clinical-core/test/conformance/patients_with_python_tier.jsonl
// (generated by tools/training/export_conformance_patients.py) through
// clinical-core's triage() in hybrid mode — proving the TypeScript port is
// a 1:1 match for Python's predict_triage before rules_first ever ships.
// See DECISIONS.md §33 / Round 6 rebuild plan Phase 1.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { createInterface } from "node:readline";
import { createReadStream } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { triage } from "../../src/triage.js";
import type { TreeJson } from "../../src/treeEvaluator.js";

const conformanceDir = resolve(__dirname);
const patientsPath = resolve(conformanceDir, "patients_with_python_tier.jsonl");
const reportPath = resolve(conformanceDir, "REPORT.md");
const rulesFirstReportPath = resolve(conformanceDir, "RULES_FIRST_DELTA.md");
const rootDir = resolve(conformanceDir, "..", "..", "..", "..");
const treesPath = resolve(rootDir, "apps", "web", "public", "models", "triage_trees.json");
const featuresConfigPath = resolve(rootDir, "apps", "web", "public", "models", "features_config.json");

interface ConformanceRecord {
  patient_age: number;
  patient_sex: string;
  bp_systolic: number;
  bp_diastolic: number;
  heart_rate: number;
  spo2: number;
  temperature: number;
  chief_complaint: string;
  complaint_duration: string;
  location: string;
  symptoms?: string[];
  observations?: string;
  known_conditions?: string;
  current_medications?: string;
  _reference_month?: number;
  python_tier: string;
  python_confidence: number;
  python_safety_net_triggered: boolean;
}

async function readJsonl(path: string): Promise<ConformanceRecord[]> {
  const fileStream = createReadStream(path);
  const rl = createInterface({ input: fileStream, crlfDelay: Infinity });
  const records: ConformanceRecord[] = [];
  for await (const line of rl) {
    if (line.trim()) records.push(JSON.parse(line));
  }
  return records;
}

describe.skipIf(!existsSync(patientsPath))(
  "clinical-core triage() (hybrid mode) matches Python predict_triage",
  { timeout: 60000 },
  () => {
    it("agrees with the Python-labeled conformance set", async () => {
      const records = await readJsonl(patientsPath);
      const trees: TreeJson = JSON.parse(readFileSync(treesPath, "utf8"));
      const featuresConfig: { feature_names: string[] } = JSON.parse(readFileSync(featuresConfigPath, "utf8"));

      const confusion: Record<string, Record<string, number>> = {};
      const mismatches: Array<{ index: number; python: string; ts: string; patient: ConformanceRecord }> = [];

      for (let i = 0; i < records.length; i++) {
        const record = records[i]!;
        const result = triage(record, { mode: "hybrid", trees, featureNames: featuresConfig.feature_names });

        confusion[record.python_tier] ??= {};
        confusion[record.python_tier]![result.tier] = (confusion[record.python_tier]![result.tier] ?? 0) + 1;

        if (result.tier !== record.python_tier) {
          mismatches.push({ index: i, python: record.python_tier, ts: result.tier, patient: record });
        }
      }

      const n = records.length;
      const agreementPct = (((n - mismatches.length) / n) * 100).toFixed(3);

      const lines = [
        "# Hybrid-mode conformance report",
        "",
        `Generated from ${n} synthetic patients (backend/scripts/export_conformance_patients.py, seed 20260711).`,
        `Each was labeled by Python's \`predict_triage\` (production, pre-migration) and replayed through`,
        "clinical-core's `triage()` in `hybrid` mode (safety-net override -> trained model -> NEWS2 floor —",
        "the same order as the Python path).",
        "",
        `**Agreement: ${n - mismatches.length}/${n} (${agreementPct}%)**`,
        "",
        "## Confusion matrix (rows = Python tier, columns = TS tier)",
        "",
        "| Python \\ TS | ROUTINE | URGENT | EMERGENCY |",
        "|---|---|---|---|",
        ...(["ROUTINE", "URGENT", "EMERGENCY"] as const).map(
          (row) =>
            `| ${row} | ${confusion[row]?.ROUTINE ?? 0} | ${confusion[row]?.URGENT ?? 0} | ${confusion[row]?.EMERGENCY ?? 0} |`,
        ),
        "",
        mismatches.length > 0 ? "## Mismatches (first 20)" : "## Mismatches: none",
        "",
        ...mismatches.slice(0, 20).map(
          (m) =>
            `- #${m.index}: python=${m.python} ts=${m.ts} — age=${m.patient.patient_age}, ` +
            `bp=${m.patient.bp_systolic}/${m.patient.bp_diastolic}, hr=${m.patient.heart_rate}, ` +
            `spo2=${m.patient.spo2}, temp=${m.patient.temperature}, symptoms=${JSON.stringify(m.patient.symptoms)}`,
        ),
        "",
      ];
      writeFileSync(reportPath, lines.join("\n"));

      // Hybrid mode's entire purpose is exact parity with the Python path —
      // any mismatch is a real port bug to fix, not an expected divergence.
      expect(mismatches.length, `${mismatches.length} mismatch(es) — see ${reportPath}`).toBe(0);
    });

    // Informational only (not a pass/fail gate): quantifies how the TARGET
    // architecture (rules_first — rules engine 100% authoritative, model
    // advisory-only) would have triaged the same 10k patients differently
    // from today's production (Python predict_triage, replayed above as the
    // hybrid-mode baseline). This is the delta DECISIONS §33 must record
    // when rules_first ships (Phase 4) — generated here because the same
    // conformance set and harness make it nearly free.
    it("quantifies the rules_first vs. current-production delta (informational)", async () => {
      const records = await readJsonl(patientsPath);
      const trees: TreeJson = JSON.parse(readFileSync(treesPath, "utf8"));
      const featuresConfig: { feature_names: string[] } = JSON.parse(readFileSync(featuresConfigPath, "utf8"));

      const confusion: Record<string, Record<string, number>> = {};
      const deltas: Array<{ index: number; python: string; rulesFirst: string; modelAgreed: boolean }> = [];

      for (let i = 0; i < records.length; i++) {
        const record = records[i]!;
        const result = triage(record, { mode: "rules_first", trees, featureNames: featuresConfig.feature_names });

        confusion[record.python_tier] ??= {};
        confusion[record.python_tier]![result.tier] = (confusion[record.python_tier]![result.tier] ?? 0) + 1;

        if (result.tier !== record.python_tier) {
          deltas.push({ index: i, python: record.python_tier, rulesFirst: result.tier, modelAgreed: result.modelAgreed ?? true });
        }
      }

      const n = records.length;
      const samePct = (((n - deltas.length) / n) * 100).toFixed(3);

      const lines = [
        "# Rules-first vs. production-Python triage delta report",
        "",
        `Generated from the same ${n} synthetic patients as REPORT.md.`,
        "Compares Python's `predict_triage` (production baseline) against clinical-core's `triage()` in `rules_first` mode",
        "(the Phase 4 target architecture, where clinical-core rules are 100% authoritative and the model is advisory).",
        "",
        `**Identical classification: ${n - deltas.length}/${n} (${samePct}%)**`,
        `**Changed classification: ${deltas.length}/${n} (${(((deltas.length) / n) * 100).toFixed(3)}%)**`,
        "",
        "## Confusion matrix (rows = Python tier, columns = rules_first tier)",
        "",
        "| Python \\ RulesFirst | ROUTINE | URGENT | EMERGENCY |",
        "|---|---|---|---|",
        ...(["ROUTINE", "URGENT", "EMERGENCY"] as const).map(
          (row) =>
            `| ${row} | ${confusion[row]?.ROUTINE ?? 0} | ${confusion[row]?.URGENT ?? 0} | ${confusion[row]?.EMERGENCY ?? 0} |`,
        ),
        "",
        "## Sample deltas (first 20)",
        "",
        ...deltas.slice(0, 20).map(
          (d) => `- #${d.index}: production_python=${d.python} -> rules_first=${d.rulesFirst} (model_agreed=${d.modelAgreed})`,
        ),
        "",
      ];
      writeFileSync(rulesFirstReportPath, lines.join("\n"));
      expect(n).toBeGreaterThan(0);
    });
  },
);
