#!/usr/bin/env python3
"""
VitalNet Unified Triage Classifier — training pipeline (v3.0.0).

Replaces two previously-divergent models:
  - the "enhanced" 4-sub-model ensemble (emergency_detector + symptom_classifier
    + clinical_reasoner + VotingClassifier + CalibratedClassifierCV) that the
    backend loaded at runtime, and
  - the separately-trained single HistGradientBoostingClassifier that only the
    ONNX export pipeline used for offline/browser inference.

Those two models had different weights trained on different synthetic data,
so the online (backend) and offline (ONNX/browser) triage classifications
could disagree for the same patient — a real clinical-safety inconsistency.
This script trains ONE model and exports it to both formats so online and
offline triage are always identical.

Why a single HistGradientBoostingClassifier instead of an ensemble:
  - It is natively supported by both `shap.TreeExplainer` (exact, fast) and
    `skl2onnx` (for browser inference) — no monkey-patching or sub-model
    extraction needed.
  - A single boosted-tree model with well-chosen `class_weight` and enough
    training data reaches emergency-recall parity with the old ensemble
    at roughly 1/8th the memory footprint and roughly 1/9th the inference
    compute (the old ensemble ran three separate models twice per
    prediction — once inside CalibratedClassifierCV's internal folds and
    again explicitly for "uncertainty" — for no measurable accuracy gain
    over a single well-tuned model in a 43-feature clinical space).
  - It loads and predicts fast enough for a decade-old laptop or a
    Raspberry-Pi-class rural clinic server, and the .onnx export is small
    enough (<1 MB) for slow/metered rural connections.

Clinical grounding for synthetic label generation
---------------------------------------------------
This project has no access to real de-identified patient data (rural PHC
records are not available for training), so labels are generated with an
evidence-informed scoring function rather than hand-picked boolean rules.
The scorer — packages/clinical-core/src/rules/engine.ts's assignTier() — is
loosely modelled on:
  - NEWS2 (Royal College of Physicians, 2017) aggregate early-warning
    scoring philosophy: score each vital parameter 0-3 by deviation from
    normal, sum to an aggregate score, and treat any single severely
    deranged parameter as an automatic escalation regardless of the
    aggregate (NEWS2's "red score" rule).
  - qSOFA (Sepsis-3, Singer et al. 2016) for suspected-infection deterioration:
    altered mentation, systolic BP <=100, tachycardia as sepsis risk signals.
  - Standard paediatric vital-sign reference ranges (APLS/PALS) for
    age-banded heart-rate and temperature thresholds in children, since
    adult NEWS2 bands are not valid for a 2-year-old.
This is a heuristic label generator for a synthetic training set, not a
validated clinical scoring instrument — see backend/app/ml/README.md for
the full explanation and limitations. The output labels are then learned
by the classifier from the full 43-feature representation (not just the
handful of features the scorer directly reads), so the trained model can
generalise beyond the scorer's exact rule boundaries.

Labeling and feature engineering (this "kills the last mirror" — see
docs/DECISIONS.md §33): this script used to carry its own ~190-line
NEWS2/qSOFA/PALS Python port of the scorer, plus its own call into
ClinicalFeatureEngineer, entirely separate from the TypeScript rules
engine/feature-engineering that packages/clinical-core ships to both the
browser and apps/api. That was the last hand-mirrored pair in the codebase.
This script now pipes every synthetic patient through
packages/clinical-core/cli.mjs (a JSONL subprocess — see _run_cli below),
so training labels and features are always generated by the EXACT SAME
code that performs real inference. Python keeps only sklearn training +
skl2onnx-to-tree-JSON export; the existing pkl==onnx==treeJSON parity
assertion (step 8 below) remains the one parity check left at training time.

Usage:
    cd tools/training
    source ../../backend/venv/bin/activate
    node ../../packages/clinical-core -v >/dev/null  # sanity: pnpm --filter @vitalnet/clinical-core build first
    python train_classifier.py

Outputs:
    backend/app/ml/models/triage_classifier.pkl   (backend: classifier + SHAP explainer)
    apps/web/public/models/triage_trees.json       (browser: compact tree ensemble,
        evaluated in pure JS by packages/clinical-core/src/treeEvaluator.ts —
        NO onnxruntime-web WASM)
    apps/web/public/models/features_config.json    (canonical feature order —
        the frontend fetches this at runtime instead of hard-coding feature
        order, eliminating an entire class of silent drift bugs)
    apps/web/tests/fixtures/golden_vectors.json     (py-labelled vectors consumed
        by packages/clinical-core/test/treeEvaluator.golden.test.ts — proves the
        offline tree evaluator == the server model on a held-out sample)

ONNX is still produced in memory (skl2onnx) as the intermediate the tree JSON is
extracted from, but it is no longer written to disk or shipped — the browser
never loads onnxruntime. See tree_export.py for the extraction + a Python
reference evaluator used to assert py-pkl == onnx == tree-JSON == JS.
"""
import json
import os
import subprocess
import sys
import pickle
import warnings
from datetime import datetime, timezone

import numpy as np
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_predict
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, recall_score

warnings.filterwarnings("ignore")

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
BACKEND_DIR = os.path.join(PROJECT_ROOT, "backend")
sys.path.insert(0, BACKEND_DIR)
sys.path.insert(0, os.path.dirname(__file__))  # for tree_export

from tree_export import onnx_to_tree_json, evaluate_tree_json  # noqa: E402

MODELS_DIR = os.path.join(BACKEND_DIR, "app", "ml", "models")
PKL_PATH = os.path.join(MODELS_DIR, "triage_classifier.pkl")
FRONTEND_MODELS_DIR = os.path.join(PROJECT_ROOT, "apps", "web", "public", "models")
FEATURES_CONFIG_PATH = os.path.join(FRONTEND_MODELS_DIR, "features_config.json")
# Offline inference (Option 6): the browser loads this compact tree JSON and
# evaluates it in pure JS — no onnxruntime-web WASM. See tree_export.py.
TREE_JSON_PATH = os.path.join(FRONTEND_MODELS_DIR, "triage_trees.json")
# Golden fixture consumed by clinical-core's vitest golden suite (not shipped to users).
GOLDEN_DIR = os.path.join(PROJECT_ROOT, "apps", "web", "tests", "fixtures")
GOLDEN_PATH = os.path.join(GOLDEN_DIR, "golden_vectors.json")
# Golden fixture for buildFeatureMap, consumed by clinical-core's
# test/features.golden.test.ts. Generated straight from engineer_features_batch
# (i.e. from clinical-core itself, via the CLI) rather than a second
# implementation — a regression snapshot, not a cross-language parity check,
# now that Python no longer maintains its own copy of this logic.
FEATURE_GOLDEN_PATH = os.path.join(GOLDEN_DIR, "golden_feature_vectors.json")

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

MODEL_VERSION = "3.1.0"
LABEL_MAP = {0: "ROUTINE", 1: "URGENT", 2: "EMERGENCY"}

# ---------------------------------------------------------------------------
# clinical-core cli.mjs subprocess bridge — the single source of labels and
# engineered features (see module docstring). Requires
# `pnpm --filter @vitalnet/clinical-core build` to have already produced
# dist/ (cli.mjs imports from there, not src/).
# ---------------------------------------------------------------------------
CLI_PATH = os.path.join(PROJECT_ROOT, "packages", "clinical-core", "cli.mjs")
CLI_BATCH_SIZE = 8000  # one subprocess spawn per batch, not per patient


def _run_cli_once(command: str, patients: list) -> list:
    payload = "\n".join(json.dumps(p) for p in patients) + "\n"
    proc = subprocess.run(
        ["node", CLI_PATH, command],
        input=payload,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"clinical-core cli.mjs {command} failed:\n{proc.stderr}")
    lines = [line for line in proc.stdout.split("\n") if line]
    if len(lines) != len(patients):
        raise RuntimeError(
            f"clinical-core cli.mjs {command}: expected {len(patients)} output "
            f"lines, got {len(lines)}"
        )
    return [json.loads(line) for line in lines]


def _run_cli(command: str, patients: list) -> list:
    results = []
    for i in range(0, len(patients), CLI_BATCH_SIZE):
        results.extend(_run_cli_once(command, patients[i:i + CLI_BATCH_SIZE]))
    return results


def assign_triage_labels(patients: list) -> list:
    """Batched replacement for the old per-patient assign_triage_label() —
    labels come from clinical-core's rules engine (rules_first semantics),
    the same code path apps/api's POST /api/submit calls at inference time."""
    return [row["label"] for row in _run_cli("label", patients)]


def engineer_features_batch(patients: list) -> list:
    """Batched replacement for the old per-patient
    ClinicalFeatureEngineer.engineer_features() calls."""
    return _run_cli("engineer-features", patients)


# A minimal but complete patient — every FeatureFormInput field present —
# used once to derive the canonical feature order from a single CLI
# round-trip instead of hardcoding it or re-deriving it in two places.
_DUMMY_PATIENT = {
    "patient_age": 40, "patient_sex": "male",
    "bp_systolic": None, "bp_diastolic": None, "spo2": None,
    "heart_rate": None, "temperature": None, "symptoms": [],
    "chief_complaint": None, "complaint_duration": None,
    "location": None, "known_conditions": None,
}
# Canonical feature order — MUST match buildFeatureMap's insertion order
# exactly (both Node's JSON.stringify and Python's json.loads preserve
# insertion order for non-numeric keys, so one CLI round-trip is enough).
FEATURE_NAMES = list(engineer_features_batch([_DUMMY_PATIENT])[0].keys())
NUM_FEATURES = len(FEATURE_NAMES)

N_PER_CLASS = 12000  # 36,000 total — large enough to generalise past label-scorer boundaries
TEST_SIZE = 0.15

DURATIONS = [
    "Less than 1 hour", "1–6 hours", "6–24 hours",
    "1–3 days", "More than 3 days",
]
LOCATIONS = [
    "Rampur Village", "Kothagudem Town", "Mumbai City", "Remote Tribal Area",
    "Rural District", "Metro Urban", "Chennai City", "Bihar Village",
]
COMPLAINTS_ROUTINE = [
    "Headache / dizziness", "Nausea / vomiting", "Weakness / fatigue", "Fever", "Other",
]
COMPLAINTS_URGENT = [
    "Chest pain / tightness", "Breathlessness / difficulty breathing", "Fever",
    "Abdominal pain", "Baby / child unwell", "Pregnancy complication",
]
COMPLAINTS_EMERGENCY = [
    "Chest pain / tightness", "Breathlessness / difficulty breathing",
    "Altered consciousness / confusion", "Seizure", "Severe bleeding", "Injury / trauma",
]
CONDITIONS_POOL = ["", "", "", "diabetes", "hypertension", "asthma", "heart disease", "copd", "kidney disease"]


# ---------------------------------------------------------------------------
# Synthetic patient generation — physiologically correlated per severity band
# ---------------------------------------------------------------------------

def _correlated_vitals(age, severity):
    """severity in {'healthy','mild','moderate','severe','critical'} — used only
    to steer generation toward realistic multi-vital syndromes (e.g. shock:
    low BP + high HR together, not independently sampled). The TRUE label is
    computed afterwards by assign_triage_labels(), independent of this hint."""
    base_hr = 75 + max(0, 18 - age) * 2 - max(0, age - 60) * 0.15
    # Age-appropriate baseline systolic BP: children run LOWER than adults
    # (~85 in infancy rising ~2/yr), so anchoring to the adult ~118 would make
    # the generator emit physiologically-impossible infants and the model would
    # never see the normal-low-BP-infant pattern it must learn (DECISIONS.md §30).
    base_bp = (85 + 2.0 * age) if age < 12 else (118 + max(0, age - 40) * 0.4)

    if severity == "healthy":
        hr = np.random.normal(base_hr, 10)
        bp_sys = np.random.normal(base_bp, 10)
        bp_dia = np.random.normal(base_bp * 0.65, 7)
        spo2 = np.random.normal(97.5, 1.2)
        temp = np.random.normal(36.9, 0.35)
    elif severity == "mild":
        hr = np.random.normal(base_hr + 12, 12)
        bp_sys = np.random.normal(base_bp + 8, 14)
        bp_dia = np.random.normal(base_bp * 0.65 + 4, 9)
        spo2 = np.random.normal(95.5, 1.8)
        temp = np.random.normal(37.6, 0.7)
    elif severity == "moderate":
        pattern = np.random.choice(["fever", "hypertensive", "hypoxic", "tachy"])
        hr = np.random.normal(base_hr + (25 if pattern == "tachy" else 15), 14)
        bp_sys = np.random.normal(base_bp + (35 if pattern == "hypertensive" else 10), 16)
        bp_dia = np.random.normal(base_bp * 0.65 + 8, 10)
        spo2 = np.random.normal(92 if pattern == "hypoxic" else 95, 2.5)
        temp = np.random.normal(39.0 if pattern == "fever" else 37.4, 0.8)
    elif severity == "severe":
        pattern = np.random.choice(["shock", "hypoxic", "hypertensive_crisis", "septic"])
        if pattern == "shock":
            hr = np.random.normal(128, 14)
            bp_sys = np.random.normal(82, 10)
        elif pattern == "hypertensive_crisis":
            hr = np.random.normal(105, 14)
            bp_sys = np.random.normal(195, 12)
        elif pattern == "septic":
            hr = np.random.normal(118, 12)
            bp_sys = np.random.normal(95, 12)
        else:
            hr = np.random.normal(110, 15)
            bp_sys = np.random.normal(base_bp, 18)
        bp_dia = np.random.normal(bp_sys * 0.62, 10)
        spo2 = np.random.normal(88 if pattern == "hypoxic" else 93, 3)
        temp = np.random.normal(39.3 if pattern == "septic" else 37.6, 1.0)
    else:  # critical
        pattern = np.random.choice([
            "profound_shock", "severe_hypoxia", "extreme_tachy", "extreme_brady", "hyperthermia", "hypothermia",
        ])
        hr = {"extreme_tachy": 155, "extreme_brady": 33}.get(pattern, np.random.normal(115, 20))
        bp_sys = 65 if pattern == "profound_shock" else np.random.normal(base_bp, 25)
        bp_dia = bp_sys * 0.6
        spo2 = 82 if pattern == "severe_hypoxia" else np.random.normal(90, 5)
        temp = {"hyperthermia": 41.2, "hypothermia": 33.5}.get(pattern, np.random.normal(37.5, 1.2))

    return dict(
        hr=int(np.clip(hr, 25, 220)),
        bp_sys=int(np.clip(bp_sys, 50, 260)),
        bp_dia=int(np.clip(bp_dia, 25, 160)),
        spo2=int(np.clip(spo2, 60, 100)),
        temp=round(float(np.clip(temp, 30.0, 43.0)), 1),
    )


SEVERITY_SYMPTOM_PROBS = {
    "healthy":  dict(chest_pain=0.01, breathlessness=0.01, high_fever=0.02, severe_headache=0.02,
                      persistent_vomiting=0.01, severe_abdominal_pain=0.01),
    "mild":     dict(chest_pain=0.05, breathlessness=0.08, high_fever=0.15, severe_headache=0.10,
                      persistent_vomiting=0.08, severe_abdominal_pain=0.08),
    "moderate": dict(chest_pain=0.25, breathlessness=0.30, high_fever=0.35, severe_headache=0.20,
                      persistent_vomiting=0.18, severe_abdominal_pain=0.20, weakness_one_side=0.03),
    "severe":   dict(chest_pain=0.45, breathlessness=0.50, high_fever=0.40, severe_headache=0.15,
                      persistent_vomiting=0.15, severe_abdominal_pain=0.20, weakness_one_side=0.10,
                      difficulty_speaking=0.08, severe_bleeding=0.05, seizure=0.03,
                      altered_consciousness=0.06, swelling_face_throat=0.02),
    "critical": dict(chest_pain=0.35, breathlessness=0.55, high_fever=0.30, weakness_one_side=0.12,
                      difficulty_speaking=0.10, severe_bleeding=0.15, seizure=0.15,
                      altered_consciousness=0.30, swelling_face_throat=0.05),
}


# Monsoon months (India's dengue/malaria/leptospirosis/cholera season) and
# the rural/tribal location terms that carry the higher exposure — mirrors
# ClinicalFeatureEngineer._seasonal_disease_risk / _geographic_disease_risk
# (docs/DECISIONS.md §23). Used here to give those two features a REAL,
# learnable correlation with the resulting label, via the symptom mix a
# patient presents with — not by referencing month/location directly in
# assign_triage_labels(), which stays decoupled from generation context.
MONSOON_MONTHS = (6, 7, 8, 9)
RURAL_LOCATION_TERMS = ("village", "rural", "remote", "tribal")


def _is_rural(location: str) -> bool:
    loc = location.lower()
    return any(term in loc for term in RURAL_LOCATION_TERMS)


def _sample_symptoms(severity, reference_month=None, location=""):
    probs = dict(SEVERITY_SYMPTOM_PROBS[severity])
    if reference_month in MONSOON_MONTHS and _is_rural(location):
        for key in ("high_fever", "severe_headache", "persistent_vomiting"):
            if key in probs:
                probs[key] = min(probs[key] * 1.6, 0.65)
    return [s for s, p in probs.items() if np.random.random() < p]


def _pick_complaint(symptoms, severity):
    if "chest_pain" in symptoms:
        return "Chest pain / tightness"
    if "breathlessness" in symptoms:
        return "Breathlessness / difficulty breathing"
    if "seizure" in symptoms:
        return "Seizure"
    if "severe_bleeding" in symptoms:
        return "Severe bleeding"
    if "altered_consciousness" in symptoms:
        return "Altered consciousness / confusion"
    if "high_fever" in symptoms:
        return "Fever"
    pool = {"healthy": COMPLAINTS_ROUTINE, "mild": COMPLAINTS_ROUTINE,
            "moderate": COMPLAINTS_URGENT, "severe": COMPLAINTS_EMERGENCY,
            "critical": COMPLAINTS_EMERGENCY}[severity]
    return np.random.choice(pool)


def _pick_duration(severity):
    if severity in ("severe", "critical"):
        return np.random.choice(["Less than 1 hour", "1–6 hours"], p=[0.6, 0.4])
    if severity == "moderate":
        return np.random.choice(["Less than 1 hour", "1–6 hours", "6–24 hours"], p=[0.3, 0.4, 0.3])
    return np.random.choice(DURATIONS, p=[0.1, 0.15, 0.25, 0.25, 0.25])


# Probability that a given optional vital is simply not measured, per vital.
# Reflects the rural reality: an ASHA worker very often has a thermometer but no
# BP cuff or pulse-oximeter. Training on these missing-data patterns (rather than
# only complete vitals) makes the model robust to the input distribution it will
# actually see in the field. BP and SpO2 are the most commonly unavailable.
MISSING_VITAL_PROB = {
    "bp_systolic": 0.28, "bp_diastolic": 0.28,
    "spo2": 0.22, "heart_rate": 0.12, "temperature": 0.06,
}


def _apply_missing_vitals(vitals: dict) -> dict:
    """Randomly blank out some vitals to simulate incomplete field data.
    BP systolic/diastolic drop together (same cuff). Returns a copy."""
    v = dict(vitals)
    if np.random.random() < MISSING_VITAL_PROB["bp_systolic"]:
        v["bp_sys"] = None
        v["bp_dia"] = None
    if np.random.random() < MISSING_VITAL_PROB["spo2"]:
        v["spo2"] = None
    if np.random.random() < MISSING_VITAL_PROB["heart_rate"]:
        v["hr"] = None
    if np.random.random() < MISSING_VITAL_PROB["temperature"]:
        v["temp"] = None
    return v


def _sample_age(severity, pediatric):
    """Adult ages follow an exponential (most patients are working-age adults).
    When `pediatric`, draw a child age skewed young (infants/toddlers) so the
    model sees enough normal-for-age paediatric physiology to learn the age
    interaction — the fix for the documented infant over-triage
    (MODEL_CARD.md / DECISIONS.md §30). Roughly half of paediatric draws are
    under 2, where adult vital bands are most wrong."""
    if pediatric:
        # Mixture: heavy under-2 mass, tapering to 17.
        return float(np.clip(np.random.exponential(3.5), 0, 17))
    return int(np.clip(np.random.exponential(32) + (5 if severity in ("severe", "critical") else 0), 0, 95))


def generate_patient(severity, allow_missing=True, pediatric=False):
    age = _sample_age(severity, pediatric)
    sex = np.random.choice(["male", "female"], p=[0.49, 0.51])
    vitals = _correlated_vitals(age, severity)
    reference_month = int(np.random.randint(1, 13))
    location = np.random.choice(LOCATIONS)

    # Edge syndromes the base severity bands under-represent — added as targeted
    # perturbations so the model sees them during training:
    #  - "silent" presentation: an elderly/diabetic patient with genuinely
    #    deranged vitals but FEW symptoms (classic silent MI / atypical sepsis),
    #    which forces the model to weight vitals, not just symptoms.
    #  - sepsis without fever: hypotension + tachycardia with a normal/low temp.
    edge = np.random.random()
    conditions = np.random.choice(CONDITIONS_POOL)
    if severity in ("moderate", "severe", "critical") and edge < 0.08 and age >= 55:
        symptoms = []  # silent presentation — deranged vitals, no volunteered symptoms
        conditions = np.random.choice(["diabetes", "heart disease", "hypertension"])
    elif severity in ("severe", "critical") and edge < 0.16:
        # sepsis-without-fever pattern
        vitals["bp_sys"] = int(np.clip(np.random.normal(92, 8), 78, 104))
        vitals["hr"] = int(np.clip(np.random.normal(116, 10), 100, 140))
        vitals["temp"] = round(float(np.clip(np.random.normal(36.6, 0.5), 35.5, 37.6)), 1)
        symptoms = _sample_symptoms(severity, reference_month, location)
    else:
        symptoms = _sample_symptoms(severity, reference_month, location)

    if allow_missing:
        vitals = _apply_missing_vitals(vitals)

    complaint = _pick_complaint(symptoms, severity)
    duration = _pick_duration(severity)

    return {
        "patient_age": age,
        "patient_sex": sex,
        "bp_systolic": vitals["bp_sys"],
        "bp_diastolic": vitals["bp_dia"],
        "spo2": vitals["spo2"],
        "heart_rate": vitals["hr"],
        "temperature": vitals["temp"],
        "symptoms": symptoms,
        "chief_complaint": complaint,
        "complaint_duration": duration,
        "location": location,
        "known_conditions": conditions,
        "observations": "",
        "current_medications": "",
        # Training-only context (never present on a real IntakeForm submission
        # — engineer_features()/_engineer_contextual_features() falls back to
        # the real current month when absent). Lets seasonal_risk vary across
        # the synthetic training set instead of being constant (docs/DECISIONS.md §23).
        "_reference_month": reference_month,
    }


def build_dataset(n_per_class: int = N_PER_CLASS):
    """Generate patients across the full severity spectrum, then assign the
    TRUE label independently via clinical-core's rules engine
    (assign_triage_labels, batched through cli.mjs). Stratify by rejection
    sampling so each of the 3 classes has n_per_class examples — this avoids
    the label leaking directly from the generation bucket (a patient
    generated as 'severe' that happens to roll mild vitals is correctly
    labelled ROUTINE/URGENT, not forced to EMERGENCY). Generation happens in
    CLI_BATCH_SIZE batches (one subprocess spawn per batch, not per patient)
    — the same stratification semantics as the old per-patient loop, just
    with the labeling done CLI_BATCH_SIZE patients at a time."""
    buckets = {0: [], 1: [], 2: []}
    severities = ["healthy", "mild", "moderate", "severe", "critical"]
    severity_weights = [0.30, 0.22, 0.22, 0.16, 0.10]  # oversample severe/critical for label yield

    # Fraction of draws forced to paediatric ages (<18, skewed to infants).
    # The natural adult-exponential age draw yields only ~1.7% infants, far too
    # few for the model to learn age-normalised vitals — the root cause of the
    # documented infant over-triage. Oversampling here (paired with the
    # age-aware label scorer + age-appropriate BP generation above) is the fix.
    PEDIATRIC_FRACTION = 0.22

    print(f"[1/9] Generating synthetic patients in batches of {CLI_BATCH_SIZE} "
          f"(target {n_per_class}/class, {NUM_FEATURES} features, "
          f"~{int(PEDIATRIC_FRACTION*100)}% paediatric), labeling via clinical-core cli.mjs ...")
    attempts = 0
    while min(len(v) for v in buckets.values()) < n_per_class:
        batch = []
        for _ in range(CLI_BATCH_SIZE):
            severity = np.random.choice(severities, p=severity_weights)
            pediatric = np.random.random() < PEDIATRIC_FRACTION
            batch.append(generate_patient(severity, pediatric=pediatric))
        labels = assign_triage_labels(batch)
        attempts += len(batch)
        for patient, label in zip(batch, labels):
            if len(buckets[label]) < n_per_class:
                buckets[label].append(patient)
        counts = {LABEL_MAP[k]: len(v) for k, v in buckets.items()}
        print(f"       ...{attempts} generated, progress: {counts}")

    patients, labels = [], []
    for label, plist in buckets.items():
        patients.extend(plist)
        labels.extend([label] * len(plist))

    print(f"       Done in {attempts} draws. Final counts: "
          f"{ {LABEL_MAP[k]: len(v) for k, v in buckets.items()} }")
    return patients, np.array(labels)


def main():
    patients, y = build_dataset()

    print("[2/9] Engineering features (via clinical-core cli.mjs) ...")
    feature_maps = engineer_features_batch(patients)
    X = np.array([
        [fm[name] for name in FEATURE_NAMES]
        for fm in feature_maps
    ], dtype=np.float32)
    assert X.shape[1] == NUM_FEATURES

    feat_rng = np.random.default_rng(RANDOM_SEED)
    feat_idx = feat_rng.choice(len(patients), size=min(240, len(patients)), replace=False)
    feature_golden = [{"input": patients[i], "features": feature_maps[i]} for i in feat_idx]
    os.makedirs(GOLDEN_DIR, exist_ok=True)
    with open(FEATURE_GOLDEN_PATH, "w") as f:
        json.dump(feature_golden, f, indent=2, sort_keys=True)
    print(f"       golden_feature_vectors.json saved: {FEATURE_GOLDEN_PATH} ({len(feature_golden)} vectors)")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_SEED, stratify=y
    )
    print(f"       Train: {len(X_train)}   Test: {len(X_test)}")

    print("[3/9] Training HistGradientBoostingClassifier ...")
    # Class weights favour EMERGENCY recall — a missed emergency is far more
    # costly than a false-positive urgent flag in this clinical context.
    # max_leaf_nodes caps each tree's size — the primary lever on the shipped
    # triage_trees.json footprint (what a decade-old phone downloads and parses
    # offline). 24 leaves keeps accuracy within noise of the default 31 while
    # shrinking the JSON meaningfully; the safety net + NEWS2 floor still
    # guarantee the unambiguous emergencies independent of model capacity.
    HGB_PARAMS = dict(
        max_iter=450,
        max_depth=7,
        max_leaf_nodes=24,
        # A slightly higher learning rate converges in materially FEWER boosting
        # iterations, so the shipped triage_trees.json (what a decade-old phone
        # downloads and parses) is smaller — the primary efficiency lever here.
        # Paired with a tighter early-stopping patience so training stops as
        # soon as the held-out loss plateaus rather than padding out more trees.
        learning_rate=0.09,
        l2_regularization=0.5,
        # EMERGENCY weight bumped 6->7 to protect emergency recall against the
        # faster/shorter fit and the harder age-conditional boundaries.
        class_weight={0: 1.0, 1: 2.0, 2: 7.0},
        random_state=RANDOM_SEED,
        early_stopping=True,
        validation_fraction=0.1,
        n_iter_no_change=18,
    )
    clf = HistGradientBoostingClassifier(**HGB_PARAMS)
    clf.fit(X_train, y_train)

    print("[4/9] Evaluating on held-out test set ...")
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    emergency_recall = recall_score(y_test, y_pred, labels=[2], average="macro")
    emergency_fn = int(cm[2, 0] + cm[2, 1]) if cm.shape[0] > 2 else 0

    print(f"       Accuracy: {accuracy:.4f}")
    print(classification_report(y_test, y_pred, target_names=list(LABEL_MAP.values())))
    print(f"       Confusion matrix:\n{cm}")
    print(f"       EMERGENCY recall: {emergency_recall:.4f}   False negatives: {emergency_fn}")
    if emergency_fn == 0:
        print("       Safety objective met: zero EMERGENCY cases under-triaged on the held-out test set.")
    else:
        print(f"       Note: {emergency_fn} EMERGENCY under-triaged by the MODEL — the deterministic "
              "safety net + NEWS2 floor catch the unambiguous subset at inference time.")

    print("[4b/9] Stratified 5-fold cross-validation (robustness beyond one split) ...")
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_SEED)
    cv_pred = cross_val_predict(
        HistGradientBoostingClassifier(**HGB_PARAMS),
        X, y, cv=skf,
    )
    cv_acc = accuracy_score(y, cv_pred)
    cv_emerg_recall = recall_score(y, cv_pred, labels=[2], average="macro")
    cv_cm = confusion_matrix(y, cv_pred)
    print(f"       CV accuracy: {cv_acc:.4f}   CV EMERGENCY recall: {cv_emerg_recall:.4f}")
    print(f"       CV confusion matrix:\n{cv_cm}")

    print("[4c/9] Calibration report (Expected Calibration Error) ...")
    proba_test = clf.predict_proba(X_test)
    ece = _expected_calibration_error(proba_test, y_test)
    print(f"       ECE (lower is better; 0 = perfectly calibrated): {ece:.4f}")
    print("       Note: raw boosted-tree probabilities are used as-is. A post-hoc")
    print("       calibration transform is deliberately NOT applied because it")
    print("       would have to be mirrored exactly in the JS offline evaluator to")
    print("       preserve online/offline parity; the abstention flag (low_confidence)")
    print("       is the shipped mechanism for surfacing uncertainty. See MODEL_CARD.md.")

    print("[4d/9] Realistic-prevalence calibration check (~85% ROUTINE / 12% URGENT / "
          "3% EMERGENCY, subsampled from the held-out test set — not the balanced "
          "training/test split) ...")
    from app.ml.classifier import LOW_CONFIDENCE_PROBA, LOW_CONFIDENCE_MARGIN
    rng = np.random.default_rng(RANDOM_SEED)
    X_real, y_real = _realistic_prevalence_sample(X_test, y_test, rng)
    proba_real = clf.predict_proba(X_real)
    ece_real = _expected_calibration_error(proba_real, y_real)
    sorted_proba_real = np.sort(proba_real, axis=1)
    conf_real = sorted_proba_real[:, -1]
    margin_real = sorted_proba_real[:, -1] - sorted_proba_real[:, -2]
    low_conf_rate_real = float(np.mean((conf_real < LOW_CONFIDENCE_PROBA) | (margin_real < LOW_CONFIDENCE_MARGIN)))
    acc_real = accuracy_score(y_real, proba_real.argmax(axis=1))
    n_by_class_real = {LABEL_MAP[c]: int((y_real == c).sum()) for c in (0, 1, 2)}
    print(f"       n={len(y_real)} {n_by_class_real}")
    print(f"       Accuracy under realistic prevalence: {acc_real:.4f}")
    print(f"       ECE under realistic prevalence: {ece_real:.4f} (balanced-set ECE was {ece:.4f})")
    print(f"       low_confidence abstention rate under realistic prevalence: {low_conf_rate_real:.4f}")
    print("       This validates the SAME fixed abstention thresholds (0.55 proba / 0.15")
    print("       margin) against the class distribution VitalNet actually sees in the")
    print("       field, not just the class-balanced training/test split above.")

    print("[5/9] Building SHAP TreeExplainer ...")
    import shap
    explainer = shap.TreeExplainer(clf)
    _ = explainer.shap_values(X_test[:5])  # sanity check it runs without error

    print("[6/9] Saving pkl (backend) ...")
    model_data = {
        "classifier": clf,
        "explainer": explainer,
        "feature_names": FEATURE_NAMES,
        "label_map": LABEL_MAP,
        "model_version": MODEL_VERSION,
        "training_date": datetime.now(timezone.utc).isoformat(),
        "performance_metrics": {
            "accuracy": float(accuracy),
            "emergency_recall": float(emergency_recall),
            "emergency_false_negatives": emergency_fn,
            "confusion_matrix": cm.tolist(),
            "cv_accuracy": float(cv_acc),
            "cv_emergency_recall": float(cv_emerg_recall),
            "expected_calibration_error": float(ece),
            "realistic_prevalence_accuracy": float(acc_real),
            "realistic_prevalence_ece": float(ece_real),
            "realistic_prevalence_low_confidence_rate": float(low_conf_rate_real),
            "realistic_prevalence_n_by_class": n_by_class_real,
            "n_train": len(X_train),
            "n_test": len(X_test),
        },
    }
    os.makedirs(MODELS_DIR, exist_ok=True)
    with open(PKL_PATH, "wb") as f:
        pickle.dump(model_data, f, protocol=5)
    print(f"       pkl saved: {PKL_PATH} ({os.path.getsize(PKL_PATH) / 1024:.1f} KB)")

    print("[7/9] Converting to ONNX (in memory) and extracting compact tree JSON ...")
    from skl2onnx import convert_sklearn
    from skl2onnx.common.data_types import FloatTensorType
    from onnx import helper as onnx_helper

    _orig = onnx_helper.make_attribute

    def _patched(key, value):
        if isinstance(value, (list, tuple)):
            value = [int(v) if isinstance(v, (bool, np.bool_)) else v for v in value]
        elif isinstance(value, (bool, np.bool_)):
            value = int(value)
        return _orig(key, value)

    onnx_helper.make_attribute = _patched
    try:
        onnx_model = convert_sklearn(
            clf,
            initial_types=[("float_input", FloatTensorType([None, NUM_FEATURES]))],
            target_opset=15,
            options={id(clf): {"zipmap": False}},
        )
    finally:
        onnx_helper.make_attribute = _orig

    tree_json = onnx_to_tree_json(onnx_model, NUM_FEATURES)
    tree_json.pop("_tree_index", None)
    tree_json["model_version"] = MODEL_VERSION
    tree_json["exported_at"] = datetime.now(timezone.utc).isoformat()

    os.makedirs(FRONTEND_MODELS_DIR, exist_ok=True)
    with open(TREE_JSON_PATH, "w") as f:
        json.dump(tree_json, f, separators=(",", ":"))
    print(f"       triage_trees.json saved: {TREE_JSON_PATH} "
          f"({os.path.getsize(TREE_JSON_PATH) / 1024:.1f} KB, {len(tree_json['trees'])} trees)")

    # features_config.json — canonical feature order manifest. The frontend
    # fetches this at model-load time instead of hard-coding feature order,
    # so a future feature-engineering change can never silently desync Python
    # and JS.
    features_config = {
        "feature_names": FEATURE_NAMES,
        "num_features": NUM_FEATURES,
        "model_version": MODEL_VERSION,
        "model": "HistGradientBoostingClassifier (single model, pure-JS tree evaluator offline)",
        "exported_at": datetime.now(timezone.utc).isoformat(),
    }
    with open(FEATURES_CONFIG_PATH, "w") as f:
        json.dump(features_config, f, indent=2)
    print(f"       features_config.json saved: {FEATURES_CONFIG_PATH}")

    print("[8/9] Parity — pkl == onnx == tree-JSON reference evaluator (all must agree) ...")
    import onnxruntime as onnxrt
    sess = onnxrt.InferenceSession(onnx_model.SerializeToString())
    check = X_test[: min(2000, len(X_test))]
    pkl_pred = clf.predict(check)
    onnx_pred = np.asarray(sess.run(None, {"float_input": check})[0]).ravel()
    json_pred = np.array([evaluate_tree_json(tree_json, row.tolist())[0] for row in check])
    onnx_agree = np.array_equal(pkl_pred, onnx_pred)
    json_agree = np.array_equal(pkl_pred, json_pred)
    print(f"       pkl==onnx: {onnx_agree}   pkl==treeJSON: {json_agree} "
          f"(on {len(check)} held-out samples)")
    if not (onnx_agree and json_agree):
        raise RuntimeError(
            "PARITY FAILURE — the tree JSON / onnx disagree with the pkl. "
            "Do NOT ship; the offline (JS) triage would diverge from the server."
        )
    print("       Parity OK — offline JS triage will match the server exactly.")

    print("[9/9] Writing golden vectors for the frontend JS parity test ...")
    # Draw from the 'check' subset. Store rounded features and compute the
    # expected label with the tree-JSON reference evaluator on those SAME rounded
    # features, so the JS test (same algorithm, same inputs) can match exactly.
    # The reference==sklearn==onnx equivalence is separately asserted in step 8
    # on unrounded data, so the chain JS==reference==sklearn==onnx holds.
    rng = np.random.default_rng(RANDOM_SEED)
    idx = rng.choice(len(check), size=min(300, len(check)), replace=False)
    golden = []
    for i in idx:
        feats = [round(float(v), 6) for v in check[i].tolist()]
        golden.append({"features": feats, "expected_class": int(evaluate_tree_json(tree_json, feats)[0])})
    os.makedirs(GOLDEN_DIR, exist_ok=True)
    with open(GOLDEN_PATH, "w") as f:
        json.dump({"model_version": MODEL_VERSION, "vectors": golden}, f)
    print(f"       golden_vectors.json saved: {GOLDEN_PATH} ({len(golden)} vectors)")

    print("\nDone. Backend loads the .pkl; the browser loads triage_trees.json + "
          "features_config.json and evaluates in pure JS (no onnxruntime).")


def _realistic_prevalence_sample(X: np.ndarray, y: np.ndarray, rng: np.random.Generator,
                                  routine_frac: float = 0.85, urgent_frac: float = 0.12,
                                  emergency_frac: float = 0.03):
    """
    Subsamples the (class-balanced) held-out test set down to a realistic
    rural-PHC class prevalence — mostly ROUTINE, a minority URGENT, a small
    EMERGENCY tail — WITHOUT touching training data or introducing any new
    generated patients. All available ROUTINE rows are kept (they're the
    scarce resource once inverted); URGENT/EMERGENCY are subsampled down to
    match the target proportions relative to that ROUTINE count. Used to
    validate calibration/abstention thresholds against the distribution
    VitalNet actually sees in the field, not just the balanced test split
    used for the primary accuracy/recall numbers (docs/DECISIONS.md §23).
    """
    idx_by_class = {c: np.where(y == c)[0] for c in (0, 1, 2)}
    n_routine = len(idx_by_class[0])
    total = int(n_routine / routine_frac)
    n_urgent = min(len(idx_by_class[1]), int(total * urgent_frac))
    n_emergency = min(len(idx_by_class[2]), int(total * emergency_frac))
    sel_urgent = rng.choice(idx_by_class[1], size=n_urgent, replace=False)
    sel_emergency = rng.choice(idx_by_class[2], size=n_emergency, replace=False)
    idx = np.concatenate([idx_by_class[0], sel_urgent, sel_emergency])
    rng.shuffle(idx)
    return X[idx], y[idx]


def _expected_calibration_error(proba: np.ndarray, y_true: np.ndarray, n_bins: int = 10) -> float:
    """Standard ECE over the predicted-class confidence, 10 equal-width bins."""
    conf = proba.max(axis=1)
    pred = proba.argmax(axis=1)
    correct = (pred == y_true).astype(float)
    ece, n = 0.0, len(y_true)
    for b in range(n_bins):
        lo, hi = b / n_bins, (b + 1) / n_bins
        mask = (conf > lo) & (conf <= hi)
        if mask.sum() == 0:
            continue
        ece += (mask.sum() / n) * abs(correct[mask].mean() - conf[mask].mean())
    return float(ece)


if __name__ == "__main__":
    main()
