// frontend/src/lib/outbox.js — Round 6 rebuild plan, Phase 5.
// The unified offline outbox: a generic event queue replacing the
// case-submission-only submission_queue (offlineQueue.js, now retired).
// Every queued action is { event_id, type, payload, created_at, attempts,
// status, last_error }. event_id is generated by the caller (syncStore.js)
// and doubles as the server-side idempotency key — for type:'case.submit'
// it's the SAME uuid as case_records.client_id and the X-Event-Id header
// apps/api's idempotency middleware dedupes on, so there is exactly one id
// per logical submission end to end, not three independently-generated ones.
//
// Only 'case.submit' exists as an event type today (doctor actions stay
// online-only per the Round 6 rebuild plan's item 3 decision) — the schema
// is generic so a future offline-capable action can reuse this store
// without another IndexedDB version bump.
//
// SHARED-DEVICE SAFETY: every row carries owner_id — the auth user id of the
// worker who queued it. The PHC tablets these run on are handed between ASHA
// workers, so the drain loop and the dead-letter UI MUST only ever surface a
// row to the same worker who created it. Without this, Worker B logging in
// after Worker A queued a case offline would submit A's patient data under
// B's identity/JWT (getPendingEvents) and see A's patient name/complaint in
// the dead-letter list (getDeadLetters). Both are scoped by owner_id below.
import { getOfflineDB } from './offlineDB'

const STORE_NAME = 'outbox'
const MAX_PENDING = 50
const RECOVERY_STATUS = 'recovery_required'
export const OUTBOX_STALE_RETENTION_MS = 7 * 24 * 60 * 60 * 1000


function notifyOutboxChange() {
  window.dispatchEvent(new CustomEvent('offline-queue-changed'))
}

// ── Outbox payload encryption for shared-tablet PHI isolation (VN-2026-08-C4-03) ──
// Generates an ephemeral AES-256-GCM session key on login stored in sessionStorage.
// When Worker A logs out, sessionStorage is wiped. Worker B inspecting IndexedDB
// directly only sees encrypted ciphertext blobs { _encrypted: true, iv, ct }.

async function getSessionOutboxKey() {
  const stored = typeof sessionStorage !== 'undefined' ? sessionStorage.getItem('vn_outbox_key') : null
  if (stored) {
    const raw = Uint8Array.from(atob(stored), (c) => c.charCodeAt(0))
    return crypto.subtle.importKey('raw', raw, { name: 'AES-GCM' }, false, ['encrypt', 'decrypt'])
  }
  const key = await crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, true, ['encrypt', 'decrypt'])
  const exported = await crypto.subtle.exportKey('raw', key)
  const b64 = btoa(String.fromCharCode(...new Uint8Array(exported)))
  if (typeof sessionStorage !== 'undefined') {
    sessionStorage.setItem('vn_outbox_key', b64)
  }
  return key
}

export async function encryptOutboxPayload(payload) {
  try {
    const key = await getSessionOutboxKey()
    const iv = crypto.getRandomValues(new Uint8Array(12))
    const encoded = new TextEncoder().encode(JSON.stringify(payload))
    const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, encoded)
    return { _encrypted: true, iv: Array.from(iv), ct: Array.from(new Uint8Array(ct)) }
  } catch (err) {
    console.warn('[VitalNet] Outbox encryption fallback to plaintext', err)
    return payload
  }
}

export async function decryptOutboxPayload(payload) {
  if (!payload || !payload._encrypted) return payload
  try {
    const key = await getSessionOutboxKey()
    const iv = new Uint8Array(payload.iv)
    const ct = new Uint8Array(payload.ct)
    const decrypted = await crypto.subtle.decrypt({ name: 'AES-GCM', iv }, key, ct)
    return JSON.parse(new TextDecoder().decode(decrypted))
  } catch (err) {
    console.warn('[VitalNet] Outbox payload decryption failed (different session/worker key)', err)
    return null
  }
}

/**
 * Queue an event for later sync. No token stored — fresh token fetched at
 * sync time. ownerId is the queuing worker's auth user id; it gates who may
 * later drain or view this row (see module header). Payload is encrypted
 * at rest with the worker's session key (VN-2026-08-C4-03).
 */
export async function enqueue(eventId, type, payload, ownerId) {
  const pendingCount = await getPendingCount()
  if (pendingCount >= MAX_PENDING) {
    console.warn(`[VitalNet] Offline outbox is full (${MAX_PENDING} pending items). Cannot queue more.`)
    throw new Error(`Offline queue is full (${MAX_PENDING} items). Please sync before submitting more cases.`)
  }

  const encryptedPayload = await encryptOutboxPayload(payload)
  const db = await getOfflineDB()
  await db.put(STORE_NAME, {
    event_id: eventId,
    owner_id: ownerId ?? null,
    type,
    payload: encryptedPayload,
    created_at: new Date().toISOString(),
    attempts: 0,
    status: 'pending',
    last_error: null,
  })
  notifyOutboxChange()
}

export async function dequeue(eventId) {
  const db = await getOfflineDB()
  await db.delete(STORE_NAME, eventId)
  notifyOutboxChange()
}

/**
 * Pending events owned by `ownerId`, oldest first — the FIFO drain order
 * processQueue() uses. Scoped by owner so a worker never drains (submits
 * under their own JWT) a case another worker queued on the same device.
 * Returns [] when ownerId is falsy: with no known identity there is nothing
 * safe to submit. Decrypts payloads using the active session key.
 */
export async function getPendingEvents(ownerId) {
  if (!ownerId) return []
  const db = await getOfflineDB()
  const all = await db.getAllFromIndex(STORE_NAME, 'created_at')
  const owned = all.filter((e) => e.status === 'pending' && e.owner_id === ownerId)
  const decrypted = []
  for (const item of owned) {
    const plain = await decryptOutboxPayload(item.payload)
    if (plain) {
      decrypted.push({ ...item, payload: plain })
    }
  }
  return decrypted
}

/**
 * Total pending count across ALL owners. This is a device-level indicator
 * only (the "N pending" badge and the capacity guard) — it exposes no PHI,
 * just a number — so it is intentionally not owner-scoped.
 */
export async function getPendingCount() {
  const db = await getOfflineDB()
  return db.countFromIndex(STORE_NAME, 'status', 'pending')
}

/**
 * Count legacy rows that cannot be safely attributed to a worker. This is an
 * aggregate-only signal: callers must not receive the payload or identifiers.
 */
export async function getRecoveryRequiredCount() {
  const db = await getOfflineDB()
  return db.countFromIndex(STORE_NAME, 'status', RECOVERY_STATUS)
}

/**
 * Aggregate count of this worker's pending rows older than the documented
 * review window. The payload is never returned to the caller.
 */
export async function getStalePendingCount(ownerId, now = Date.now()) {
  if (!ownerId) return 0
  const db = await getOfflineDB()
  const all = await db.getAllFromIndex(STORE_NAME, 'status', 'pending')
  return all.filter((row) => (
    row.owner_id === ownerId
    && Number.isFinite(Date.parse(row.created_at))
    && now - Date.parse(row.created_at) >= OUTBOX_STALE_RETENTION_MS
  )).length
}

/**
 * Explicitly purge only this worker's stale pending rows after user review.
 * This is never called automatically and cannot affect another worker's rows.
 */
export async function purgeStalePending(ownerId, now = Date.now()) {
  if (!ownerId) return 0
  const db = await getOfflineDB()
  const all = await db.getAllFromIndex(STORE_NAME, 'status', 'pending')
  let removed = 0
  for (const row of all) {
    if (
      row.owner_id === ownerId
      && Number.isFinite(Date.parse(row.created_at))
      && now - Date.parse(row.created_at) >= OUTBOX_STALE_RETENTION_MS
    ) {
      await db.delete(STORE_NAME, row.event_id)
      removed += 1
    }
  }
  if (removed > 0) notifyOutboxChange()
  return removed
}

/**
 * Permanently purge ownerless legacy recovery records after an explicit
 * device-level confirmation. This never touches pending, dead-lettered, or
 * currently owned rows.
 */
export async function purgeRecoveryRequired() {
  const db = await getOfflineDB()
  const rows = await db.getAllFromIndex(STORE_NAME, 'status', RECOVERY_STATUS)
  for (const row of rows) {
    await db.delete(STORE_NAME, row.event_id)
  }
  if (rows.length > 0) notifyOutboxChange()
  return rows.length
}

/**
 * A permanent (4xx) failure — surfaced to the UI as a dead-letter list
 * instead of being silently dropped or retried forever.
 */
export async function markDead(eventId, lastError) {
  const db = await getOfflineDB()
  const tx = db.transaction(STORE_NAME, 'readwrite')
  const row = await tx.store.get(eventId)
  if (row) {
    row.status = 'dead'
    row.last_error = lastError
    await tx.store.put(row)
  }
  await tx.done
  notifyOutboxChange()
}

export async function incrementAttempts(eventId) {
  const db = await getOfflineDB()
  const tx = db.transaction(STORE_NAME, 'readwrite')
  const row = await tx.store.get(eventId)
  if (row) {
    row.attempts = (row.attempts || 0) + 1
    await tx.store.put(row)
  }
  await tx.done
}

/**
 * Dead-lettered events owned by `ownerId`. Owner-scoped because these rows
 * carry patient_name/chief_complaint that the dead-letter UI renders — an
 * unscoped list would show one worker another worker's patient PHI on a
 * shared device. Returns [] when ownerId is falsy.
 */
export async function getDeadLetters(ownerId) {
  if (!ownerId) return []
  const db = await getOfflineDB()
  const all = await db.getAllFromIndex(STORE_NAME, 'status', 'dead')
  const owned = all.filter((e) => e.owner_id === ownerId)
  const decrypted = []
  for (const item of owned) {
    const plain = await decryptOutboxPayload(item.payload)
    decrypted.push({
      ...item,
      payload: plain || { patient_name: '[Encrypted from prior session]', chief_complaint: 'Offline submission' },
    })
  }
  return decrypted
}

export async function getDeadLetterCount(ownerId) {
  const dead = await getDeadLetters(ownerId)
  return dead.length
}

/** Moves a dead-lettered event back to pending so the next drain retries it. */
export async function retryDeadLetter(eventId) {
  const db = await getOfflineDB()
  const tx = db.transaction(STORE_NAME, 'readwrite')
  const row = await tx.store.get(eventId)
  if (row) {
    row.status = 'pending'
    row.last_error = null
    row.attempts = 0
    await tx.store.put(row)
  }
  await tx.done
  notifyOutboxChange()
}

/** Discards a dead-lettered event permanently (worker has reviewed and dismissed it). */
export async function discardDeadLetter(eventId) {
  await dequeue(eventId)
}
