// frontend/src/lib/outbox.js — Round 6 rebuild plan, Phase 5.
// The unified offline outbox: a generic event queue replacing the
// case-submission-only submission_queue (offlineQueue.js, now retired).
// Every queued action is { event_id, type, payload, created_at, attempts,
// status, last_error }. event_id is generated by the caller (syncStore.js)
// and doubles as the server-side idempotency key — for type:'case.submit'
// it's the SAME uuid as case_records.client_id and the X-Event-Id header
// apps/api's idempotency middleware dedupes on, so there is exactly one id
// per logical submission end to end, not three independently-generated ones.
//
// Only 'case.submit' exists as an event type today (doctor actions stay
// online-only per the Round 6 rebuild plan's item 3 decision) — the schema
// is generic so a future offline-capable action can reuse this store
// without another IndexedDB version bump.
import { getOfflineDB } from './offlineDB'

const STORE_NAME = 'outbox'
const MAX_PENDING = 50

function notifyOutboxChange() {
  window.dispatchEvent(new CustomEvent('offline-queue-changed'))
}

/**
 * Queue an event for later sync. No token stored — fresh token fetched at
 * sync time. Throws if the PENDING (not dead-lettered) count is already at
 * capacity — dead letters never block new submissions; they're a separate,
 * user-visible surface (getDeadLetters) the worker clears explicitly.
 */
export async function enqueue(eventId, type, payload) {
  const pendingCount = await getPendingCount()
  if (pendingCount >= MAX_PENDING) {
    console.warn(`[VitalNet] Offline outbox is full (${MAX_PENDING} pending items). Cannot queue more.`)
    throw new Error(`Offline queue is full (${MAX_PENDING} items). Please sync before submitting more cases.`)
  }

  const db = await getOfflineDB()
  await db.put(STORE_NAME, {
    event_id: eventId,
    type,
    payload,
    created_at: new Date().toISOString(),
    attempts: 0,
    status: 'pending',
    last_error: null,
  })
  notifyOutboxChange()
}

export async function dequeue(eventId) {
  const db = await getOfflineDB()
  await db.delete(STORE_NAME, eventId)
  notifyOutboxChange()
}

/** All pending events, oldest first — the FIFO drain order processQueue() uses. */
export async function getPendingEvents() {
  const db = await getOfflineDB()
  const all = await db.getAllFromIndex(STORE_NAME, 'created_at')
  return all.filter((e) => e.status === 'pending')
}

export async function getPendingCount() {
  const db = await getOfflineDB()
  return db.countFromIndex(STORE_NAME, 'status', 'pending')
}

/**
 * A permanent (4xx) failure — surfaced to the UI as a dead-letter list
 * instead of being silently dropped or retried forever.
 */
export async function markDead(eventId, lastError) {
  const db = await getOfflineDB()
  const tx = db.transaction(STORE_NAME, 'readwrite')
  const row = await tx.store.get(eventId)
  if (row) {
    row.status = 'dead'
    row.last_error = lastError
    await tx.store.put(row)
  }
  await tx.done
  notifyOutboxChange()
}

export async function incrementAttempts(eventId) {
  const db = await getOfflineDB()
  const tx = db.transaction(STORE_NAME, 'readwrite')
  const row = await tx.store.get(eventId)
  if (row) {
    row.attempts = (row.attempts || 0) + 1
    await tx.store.put(row)
  }
  await tx.done
}

export async function getDeadLetters() {
  const db = await getOfflineDB()
  return db.getAllFromIndex(STORE_NAME, 'status', 'dead')
}

export async function getDeadLetterCount() {
  const db = await getOfflineDB()
  return db.countFromIndex(STORE_NAME, 'status', 'dead')
}

/** Moves a dead-lettered event back to pending so the next drain retries it. */
export async function retryDeadLetter(eventId) {
  const db = await getOfflineDB()
  const tx = db.transaction(STORE_NAME, 'readwrite')
  const row = await tx.store.get(eventId)
  if (row) {
    row.status = 'pending'
    row.last_error = null
    row.attempts = 0
    await tx.store.put(row)
  }
  await tx.done
  notifyOutboxChange()
}

/** Discards a dead-lettered event permanently (worker has reviewed and dismissed it). */
export async function discardDeadLetter(eventId) {
  await dequeue(eventId)
}
